### ISSUE TITLE
can translate to chinese?

### ISSUE THREAD

**Issue by greasebig** [voidoperator/leelo#3]
can translate to chinese?

**Comment by greasebig** [comment]
can translate to chinese? and can you provide the apk download link on the store?

**Comment by voidoperator** [comment]
> can translate to chinese? and can you provide the apk download link on the store?

theoretically it can translate to any language that the google translate API can translate to. simple to change the language in the variable translateApi inside of utilities.js. the url string reads `sl=auto&tl=es`.

sl = source language, set to automatic by default
tl = translation language, set to spanish by default (this is what you can change to chinese)


might be worth adding a feature in the near future to let the user select the language of choice.

also, there is no apk. it's open source. you can just fork this repo and run npm install, npm start. refer to the readme docs.

**Comment by greasebig** [comment]
> > can translate to chinese? and can you provide the apk download link on the store?
> 
> theoretically it can translate to any language that the google translate API can translate to. simple to change the language in the variable translateApi inside of utilities.js. the url string reads `sl=auto&tl=es`.
> 
> sl = source language, set to 'auto' aka automatic by default tl = translation language, set to 'es' aka spanish by default (this is what you can change to chinese)
> 
> might be worth adding a feature in the near future to let the user select the language of choice.
> 
> also, there is no apk. it's open source. you can just fork this repo and run npm install, npm start. refer to the readme docs.

but, i find it difficult to install or run in myself ubuntu.
i follow the installation:
![image](https://user-images.githubusercontent.com/121388156/229264230-56123b39-da2a-44e3-a3be-e248e4fd7ae1.png)
and i get this:
![image](https://user-images.githubusercontent.com/121388156/229264307-4237086e-0375-4c1a-90c6-c5b8a4eb7925.png)

**Comment by greasebig** [comment]
![image](https://user-images.githubusercontent.com/121388156/229264366-22109d3e-b377-496f-89ce-ffeb5f92f158.png)
